### ISSUE TITLE
ValidationError on BooleanField

### ISSUE THREAD

**Issue by sheiun** [MeanPug/django-gsheets#5]
When I pull `TRUE` or `FALSE` value from sheet it shows:

```bash
Exception has occurred: ValidationError
['“FALSE” value must be either True or False.']
```

But when I type `True` in sheet, it cast into all uppercase.

**Comment by steinbachr** [comment]
@sheiun one thing you should be able to do as a workaround is define a `clean_FIELD_data` method (where `FIELD` is the name of the field - from the sheet - that you need to convert). Inside that method, set the boolean value as appropriate

**Comment by sheiun** [comment]
@steinbachr it seems still not work after define `clean_{FIELD}_data` method in model.

**Comment by steinbachr** [comment]
one other thing to try @sheiun, can you try defining a `clean_row_data` staticmethod on the model subclassing the mixin? That method takes `row_data` (a `dict` of row data from the sheet prior to upsert) and returns a `dict` of the data which will be used for the upsert operation. Can you try doing the transform there?

**Comment by sheiun** [comment]
> 
> 
> one other thing to try @sheiun, can you try defining a `clean_row_data` staticmethod on the model subclassing the mixin? That method takes `row_data` (a `dict` of row data from the sheet prior to upsert) and returns a `dict` of the data which will be used for the upsert operation. Can you try doing the transform there?

Doing sth like this?

```python

class MyModel(SheetPullableMixin, models.Model):
    is_xxx = BooleanField()

    @staticmethod
    def clean_row_data(row_data):
        row_data['is_xxx'] = row_data['is_xxx'] == 'TRUE'
        return row_data
```

**Comment by sheiun** [comment]
@steinbachr Thanks it works. And if doing the change in my pull request that can also transform by using `clean_{field}_data`.
